<a href="https://colab.research.google.com/github/thzthix/Pytorch_Fundamentals/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##00. PyTorch Fundamentals

Resource notebook:https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question:https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


##Introduction to Tensors

##Creating Tensors

PyTorch ensors are created using `torch.Tensor()` =https://pytorch.org/docs/stable/tensors.html

In [ ]:
#scalar
scalar= torch.tensor(7)
scalar

tensor(7)

In [ ]:

scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
#Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX=torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                      [8,5,6],
                      [7,4,9]],
                       [[1,2,3],
                      [8,5,6],
                      [7,4,9]]])
TENSOR

tensor([[[1, 2, 3],
         [8, 5, 6],
         [7, 4, 9]],

        [[1, 2, 3],
         [8, 5, 6],
         [7, 4, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[1]

tensor([[1, 2, 3],
        [8, 5, 6],
        [7, 4, 9]])

In [ ]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3,4],
                      [8,5,6,5],
                      [7,4,9,6]],
                       [[1,2,3,5],
                      [8,5,6,7],
                      [7,4,9,8]]])
TENSOR

tensor([[[1, 2, 3, 4],
         [8, 5, 6, 5],
         [7, 4, 9, 6]],

        [[1, 2, 3, 5],
         [8, 5, 6, 7],
         [7, 4, 9, 8]]])

In [ ]:
TENSOR.shape

torch.Size([2, 3, 4])

In [ ]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3,4],
                      [8,5,6,5],
                      [7,4,9,6],
                      [7,3,4,2]],
                       [[1,2,3,5],
                      [8,5,6,7],
                      [7,4,9,8],
                         [7,3,5,2]]])
TENSOR

tensor([[[1, 2, 3, 4],
         [8, 5, 6, 5],
         [7, 4, 9, 6],
         [7, 3, 4, 2]],

        [[1, 2, 3, 5],
         [8, 5, 6, 7],
         [7, 4, 9, 8],
         [7, 3, 5, 2]]])

In [ ]:
TENSOR.shape

torch.Size([2, 4, 4])

### Random tensors

Why random tensors?

Random tensors are important because the way many nany neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers ->look at data -> update random numbers ->look at data ->update random numbers`

Torch randon tensors- https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
#create a random tensor of size
random_tensor=torch.rand(2,3,4)
random_tensor

tensor([[[0.1406, 0.4829, 0.9437, 0.9844],
         [0.5070, 0.3529, 0.9945, 0.0681],
         [0.2973, 0.4290, 0.8565, 0.2578]],

        [[0.2126, 0.0316, 0.4945, 0.1230],
         [0.4434, 0.4575, 0.2410, 0.3980],
         [0.1703, 0.3122, 0.0763, 0.8619]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
random_tensor2=torch.rand(1,2,3)
random_tensor2

tensor([[[0.6201, 0.6058, 0.5440],
         [0.4884, 0.3680, 0.7391]]])

In [ ]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, colour channels(R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###Zero and ones


In [ ]:
#Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [ ]:
#use torch,range() and get deprecated message, use torch.arrange()
two_to_eight=torch.arange(start=2,end=10,step=2)

In [ ]:
#Creating tensors like

In [ ]:
ten_zeros=torch.zeros_like(input=two_to_eight)
ten_zeros

tensor([0, 0, 0, 0])

In [ ]:
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor DataTypes
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [ ]:
#Float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9,0],
                             dtype=None, #What datatype is the tensor (e.g. float32 or float16)
                             device=None, #What device is ypur tensor on
                             requires_grad=False) #whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9., 0.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9., 0.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.,  0.])

In [ ]:
bool_tensor=float_32_tensor.type(torch.bool)
bool_tensor


tensor([ True,  True,  True, False])

In [ ]:
bool_tensor*float_32_tensor

tensor([3., 6., 9., 0.])

###Getting information from tensors (tensor attributes)
1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device -to get device from a tensor, can use `tensor.device`

In [ ]:
#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3812, 0.4867, 0.6249, 0.5327],
        [0.8297, 0.2073, 0.5915, 0.7958],
        [0.2497, 0.2564, 0.0083, 0.0902]])

In [ ]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3812, 0.4867, 0.6249, 0.5327],
        [0.8297, 0.2073, 0.5915, 0.7958],
        [0.2497, 0.2564, 0.0083, 0.0902]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [ ]:
some_tensor = torch.rand(3,4,dtype=torch.float16)
some_tensor

tensor([[0.9668, 0.5059, 0.5127, 0.4961],
        [0.9312, 0.0488, 0.4653, 0.0010],
        [0.6367, 0.8574, 0.1064, 0.8940]], dtype=torch.float16)

In [ ]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [ ]:
device = torch.device('cpu')
some_tensor.to(device)

tensor([[0.9668, 0.5059, 0.5127, 0.4961],
        [0.9312, 0.0488, 0.4653, 0.0010],
        [0.6367, 0.8574, 0.1064, 0.8940]], dtype=torch.float16)

In [ ]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [ ]:
some_tensor.view(-1,3)

tensor([[0.9668, 0.5059, 0.5127],
        [0.4961, 0.9312, 0.0488],
        [0.4653, 0.0010, 0.6367],
        [0.8574, 0.1064, 0.8940]], dtype=torch.float16)

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
#Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
#Multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [ ]:
#Subtract 10
tensor -10

tensor([-9, -8, -7])

In [ ]:
#Try out pyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

###Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **iner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer demensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3)).shape

torch.Size([3, 3])

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
#Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
#Matrix multiplication by hand
1*1+2*2+3*3

14

In [ ]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
value

CPU times: user 623 µs, sys: 0 ns, total: 623 µs
Wall time: 633 µs


tensor(14)

In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 79 µs, sys: 0 ns, total: 79 µs
Wall time: 83.4 µs


tensor(14)

###One of the most common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
torch.matmul(tensor_A,tensor_B) #torch.mm is the same as torch.matmul (It's an alias for writing less code)

RuntimeError: ignored

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of out tensors using **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
tensor_B.shape

torch.Size([3, 2])

In [ ]:
torch.matmul(tensor_A,tensor_B.T).shape

torch.Size([3, 3])

In [ ]:
#The matrix multiplication operation works when tensor_B id transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output=torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape:{output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape:torch.Size([3, 3])


###Finding the min, max, mean, sum etc (tensor aggregation)

In [ ]:
# Create a tensor
x=torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
#Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
#Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
#Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
#Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

###Finding the positional min and max

In [ ]:
#Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
#Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensor on top of each other (vstack) or side by side(hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way


In [ ]:
#Let's create a tensor
import torch
x=torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#Add a extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Change the view
z=x.view(1,10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
#Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0]=5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
#Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x,], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
rand_tensor=torch.rand(2,4,5)
rand_tensor

tensor([[[0.4437, 0.2105, 0.5379, 0.4151, 0.8274],
         [0.1041, 0.2795, 0.2631, 0.4002, 0.9411],
         [0.0685, 0.6232, 0.8460, 0.8537, 0.7005],
         [0.5544, 0.1949, 0.6217, 0.9386, 0.6131]],

        [[0.7271, 0.0153, 0.8868, 0.1896, 0.1273],
         [0.5284, 0.9066, 0.5591, 0.7040, 0.2355],
         [0.0357, 0.7059, 0.8957, 0.5646, 0.4572],
         [0.8731, 0.5414, 0.4839, 0.8096, 0.5440]]])

In [ ]:
#torch.squeeze() -removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
#torch.unsqueeze - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:

x_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
#Torch.permute - rearranges the dimensions of a target tensor in a specified order (shares same place in memory with original tensor)
x_original = torch.rand(size=(224,224,3)) #[height, width, colour_channels]

#Permute the original tensor to rearrange the axis (or dim) order
x_permuted=x_original.permute(2,0,1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #[colour_channeld, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0]=10

In [ ]:
x_permuted[0,0,0]

tensor(10.)

## Indexing (selecting data from tensors)

Indexing with PyTorch is simillar to indexing with NumPy.

In [ ]:
#Create a tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
#Let's index on the most inner bracket (last dimensions)
x[0][2][2]

tensor(9)

In [ ]:
#You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
#Get all values of 0th and 1st dmensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
#Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
#Get index 0 of 0th and 1st dimensopm amd all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
#Index on x to return 9
x[:,2,2]

#Index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)

tensor= torch.from_numpy(array) #warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
#Change the valur of array, what will this do to `tensor`?
array= array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#Change the tensor, what happens to `numpy_tensor`?
tensor= tensor+1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
tensor.dtype

torch.float32

In [ ]:
torch.arange(1.0,8.0).dtype

torch.float32

##Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers ->tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.4178, 0.0016, 0.0211, 0.0387],
        [0.9109, 0.9792, 0.3341, 0.5534],
        [0.9358, 0.9289, 0.1374, 0.4401]])
tensor([[0.3668, 0.0061, 0.0924, 0.7485],
        [0.3608, 0.3964, 0.1157, 0.6592],
        [0.7557, 0.2247, 0.7513, 0.9952]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

#Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

#Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory(good).

## 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options ti upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options..., see this post for what option to get: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these sevices allow you to rentcomputers on the cloud and access them

For 2,3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [ ]:
!nvidia-smi

Sun Aug 13 10:19:48 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g : run on GPU if available, else default to CPU

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Puting tensors (and models) on the GPU

The reason we want out tensors/models on the GPU is because using a GPU results in faster operations.

In [ ]:
#Create a tensor (default on the CPU)
import torch
tensor = torch.tensor([1,2,3],device='cpu')

#Tensors not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

###4. Moving tensors back to the CPU

In [ ]:
#If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
#To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

##Exercises & Extra-curriculum

See exercises for this notebook here: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises